services:
  - name: pairing-site-backend
    type: web
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: "5000"
